/*! Generated by redux-scfld */

export default function (getState, id, newTags) {
  const { tags } = getState();
  if (newTags) {
    return { ...tags, [id]: newTags };
  }
  delete tags[id];
  return { ...tags };
}
