/*! Generated by redux-scfld */
import action from 'redux-base/createAction';
import {
  NAMESPACE_ARTICLE,
  ARTICLE_LOAD,
} from '../../types';

export default action(NAMESPACE_ARTICLE, ARTICLE_LOAD, (getState, articleId) => {
  return fetch(`http://localhost:9090/data/${articleId}.json`)
    .then(response => response.json());

});
