/*! Generated by redux-scfld not for editing */

// Statuses
export const STATUS_PROCESS = 'STATUS_PROCESS';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_FAILURE = 'STATUS_FAILURE';

// Generated Namespaces
export const NAMESPACE_APP = 'app';
export const NAMESPACE_TAGS = 'tags';

export const NAMESPACES = [
  NAMESPACE_APP,
  NAMESPACE_TAGS,
];
// Generated Types
export const APP_LOAD = 'APP_LOAD';
export const TAGS_DEL = 'TAGS_DEL';
export const TAGS_SET = 'TAGS_SET';
