/*! Generated by redux-scfld not for editing */
'use strict';


// Statuses
export const STATUS_PROCESS = 'STATUS_PROCESS';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_FAILURE = 'STATUS_FAILURE';

// Generated Namespaces
export const NAMESPACE_APP = 'app';

export const NAMESPACES = [
    NAMESPACE_APP
];
// Generated Types
export const APP_LOAD = 'APP_LOAD';