/*! Generated by redux-scfld not for editing */

// Statuses
export const STATUS_PROCESS = 'STATUS_PROCESS';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_FAILURE = 'STATUS_FAILURE';

// Generated Namespaces
export const NAMESPACE_ARTICLE = 'article';

export const NAMESPACES = [
  NAMESPACE_ARTICLE,
];
// Generated Types
export const ARTICLE_LOAD = 'ARTICLE_LOAD';
